# Generated by Django 5.1.4 on 2025-01-06 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
