# Generated by Django 5.1.4 on 2025-01-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephile', '0003_alter_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
