# Generated by Django 5.1.4 on 2025-01-07 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephile', '0006_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactions',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 21, 2, 34, 218148)),
        ),
    ]
