# Generated by Django 5.1.4 on 2025-01-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephile', '0007_reactions_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactions',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
